[package]
name = "synthesizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

cpal = "0.15.3"
anyhow = "1.0.80"
ratatui = "0.26.1"
crossterm = "0.27.0"
fundsp = "0.16.0"
funutd = "0.14.0"
