[package]
name = "synthesizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

cpal = "0.15.3"
anyhow = "1.0.89"
ratatui = "0.29"
crossterm = "0.28"
fundsp = "0.20"
funutd = "0.16"
