mod block;
pub mod console;
mod editable_note;
mod editable_value;
mod effects_view;
mod focus_calculator;
pub mod frame_context;
mod graph;
pub mod keyboard;
mod label;
pub mod message;
mod mixer_view;
mod phrase_view;
pub mod render_app;
pub mod state;
mod title;
mod vertical_meter;
